environment:
  fast_finish: true
  matrix:
    - PYTHON: "C:\\Python26"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "32"  
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"
 
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"
 
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"
      
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"
      
    - PYTHON: "C:\\Python26-x64"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "64"        
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"
 
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"
 
    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"
 
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\Scripts\\coverage run --parallel-mode"
  
#    - PYTHON: "C:\\Python26"
#      PYTHON_VERSION: "2.6.x"
#      PYTHON_ARCH: "32"  
#      RUN: "%PYTHON%\\python"

#    - PYTHON: "C:\\Python27"
#      PYTHON_VERSION: "2.7.8"
#      PYTHON_ARCH: "32"
#      RUN: "%PYTHON%\\python"
 
#    - PYTHON: "C:\\Python33"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "32"
#      RUN: "%PYTHON%\\python"
 
#    - PYTHON: "C:\\Python34"
#      PYTHON_VERSION: "3.4.1"
#      PYTHON_ARCH: "32"
#      RUN: "%PYTHON%\\python"
      
#    - PYTHON: "C:\\Python35"
#      PYTHON_VERSION: "3.5.0"
#      PYTHON_ARCH: "32"
#      RUN: "%PYTHON%\\python"
      
#    - PYTHON: "C:\\Python26-x64"
#      PYTHON_VERSION: "2.6.x"
#      PYTHON_ARCH: "64"     
#      RUN: "%PYTHON%\\python"   
 
#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.8"
#      PYTHON_ARCH: "64"
#      RUN: "%PYTHON%\\python"
 
#    - PYTHON: "C:\\Python33-x64"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "64"
#      RUN: "%PYTHON%\\python"
 
#    - PYTHON: "C:\\Python34-x64"
#      PYTHON_VERSION: "3.4.1"
#      PYTHON_ARCH: "64"
#      RUN: "%PYTHON%\\python"

#    - PYTHON: "C:\\Python35-x64"
#      PYTHON_VERSION: "3.5.0"
#      PYTHON_ARCH: "64"
#      RUN: "%PYTHON%\\python"
 
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %APPVEYOR_BUILD_FOLDER%"
 
install:
#  - "powershell appveyor\\install.ps1"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"
  - "%PYTHON%\\Scripts\\pip install coverage==3.7.1 codecov"
  - "cd %HOME%"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "%UPnP%"
 
test: off
 
build_script:
  - "cd %HOME%"
  - "%RUN% test.py"
  - "%RUN% main.py"
  - "type output.txt"
  
on_success:
  - "dir"
  - "%PYTHON%\\Scripts\\coverage combine"
  - "%PYTHON%\\Scripts\\coverage xml"
  - "dir"
  - "%PYTHON%\\Scripts\\codecov --token=0482d032-e24c-461b-a116-f0e3dbc88734"

on_failure:
  - "type output.txt"
 
#after_test:
#  - "%WITH_COMPILER% %PYTHON%/python setup.py %DISTRIBUTIONS%"
 
artifacts:
  - path: dist\*
