engines:
  radon:
    enabled: true
    exclude_fingerprints:
    - 61999ed80a77ef3ee187cad0b8594631
  pep8:
    enabled: true
  duplication:
    enabled: true
ratings:
  paths:
  - "**.py"
languages:
  Python: true
exclude_paths:
- __init__.py
- .appveyor.yml
- .codeclimate.yml
- .gitattributes
- .travis.yml
- LICENSE
- README.md
- get-pip.py
- installpypy2.ps1
- installpypy3.ps1
- optional.txt
- requirements.txt
- test.py
- "common/__init__.py"
- "client/__init__.py"
- "server/__init__.py"

#comment to test
