engines:
  radon:
    enabled: true
    config: 
      threshold: "C"
  pep8:
    enabled: true
    checks:
      E221:
        enabled: false
      E401:
        enabled: false
      W391:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - python
ratings:
  paths:
  - "**.py"
languages:
  Python: true
exclude_paths:
- __init__.py
- .appveyor.yml
- .codeclimate.yml
- .gitattributes
- .travis.yml
- LICENSE
- README.md
- get-pip.py
- installpypy2.ps1
- installpypy3.ps1
- optional.txt
- requirements.txt
- test.py
- "common/__init__.py"
- "client/__init__.py"
- "server/__init__.py"
- "client/README.md"
- "common/README.md"
- "policies/placeholder"
- "server/README.md"
