language: c
os:
  - linux
  - osx
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
env:
  - Cov='true'
  - Cov='false'
matrix:
  allow_failures:
    - env: Cov='true'
    - os: osx
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: 
  - if [ $Cov == 'true'  ]; then coverage run main.py; fi
  - if [ $Cov == 'false' ]; then python main.py; fi
before_install:
  - echo $TRAVIS_OS_NAME;
  - if [ $TRAVIS_OS_NAME == "osx" ]; then wget https://raw.githubusercontent.com/pyca/cryptography/master/.travis/install.sh; sh install.sh; fi
  - if [ $Cov == 'true'  ]; then pip install codecov; fi
after_success:
  - if [ $Cov == 'true'  ]; then codecov --token=0482d032-e24c-461b-a116-f0e3dbc88734; fi
