language: python
repo_token: qtRAezgFkEsUBFIQrtXCxQRe2arC3H9Ta
os:
  - linux
#  - osx
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
env:
  - Cov='true' UPnP='true'
  - Cov='true' UPnP='false'
  - Cov='false' UPnP='true'
  - Cov='false' UPnP='false'
matrix:
  allow_failures:
    - env: Cov='true' UPnP='true'
    - env: Cov='true' UPnP='false'
    - os: osx
# command to install dependencies
install: 
  - if [ $UPnP == 'true'  ]; then pip install miniupnpc; fi
  - pip install -r requirements.txt
# command to run tests
script: 
  - if [ $Cov == 'true'  ]; then coverage run main.py; fi
  - if [ $Cov == 'false' ]; then python main.py; fi
before_install:
  - echo $TRAVIS_OS_NAME;
  - if [ $TRAVIS_OS_NAME == "osx" ]; then wget https://raw.githubusercontent.com/pyca/cryptography/master/.travis/install.sh; sh install.sh; fi
  - if [ $Cov == 'true'  ]; then pyver=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'); echo $pyver; if [[ $pyver =~ 3\.2\.* ]]; then pip install coverage==3.7.1 ; fi; pip install coveralls; fi
after_success:
  - if [ $Cov == 'true'  ]; then coveralls --token=0482d032-e24c-461b-a116-f0e3dbc88734; fi 
