language: python
os:
  - linux
  # - osx
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
eng:
  - Cov='true'
  - Cov='false'
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: 
  - if [ $Cov = 'true'  ];coverage run main.py
  - if [ $Cov = 'false' ];python main.py
before_install:
  - if [ $Cov = 'true'  ];pip install codecov
after_success:
  - if [ $Cov = 'true'  ];codecov --token=0482d032-e24c-461b-a116-f0e3dbc88734
