environment:
  matrix:
    - PYTHON: "C:\\Python26"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "32"  
      RUN: "%PYTHON%\\python"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\python"
 
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\python"
 
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\python"
      
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\python"
      
    - PYTHON: "C:\\Python26-x64"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "64"     
      RUN: "%PYTHON%\\python"   
 
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\python"
 
    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\python"
 
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\python"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\python"
      
    - PYTHON: "C:\\Python26"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "32"  
      RUN: "coverage run --source=Senior-Project"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      RUN: "coverage run --source=Senior-Project"
 
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"
      RUN: "coverage run --source=Senior-Project"
 
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"
      RUN: "coverage run --source=Senior-Project"
      
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"
      RUN: "coverage run --source=Senior-Project"
      
    - PYTHON: "C:\\Python26-x64"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "64"        
      RUN: "coverage run --source=Senior-Project"
 
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      RUN: "coverage run --source=Senior-Project"
 
    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "64"
      RUN: "coverage run --source=Senior-Project"
 
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      RUN: "coverage run --source=Senior-Project"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
      RUN: "coverage run --source=Senior-Project"
 
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
 
install:
#  - "powershell appveyor\\install.ps1"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"
  - "%PYTHON%\\Scripts\\pip install coveralls"
 
build: off
 
test_script:
  - "%RUN% %HOME%\\main.py"
 
#after_test:
#  - "%WITH_COMPILER% %PYTHON%/python setup.py %DISTRIBUTIONS%"
 
artifacts:
  - path: dist\*
