environment:
  fast_finish: true
  matrix:
    - PYTHON: "C:\\Python26"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "32"  
      RUN: "%PYTHON%\\Scripts\\coverage run"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\Scripts\\coverage run"
 
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\Scripts\\coverage run"
 
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\Scripts\\coverage run"
      
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"
      RUN: "%PYTHON%\\Scripts\\coverage run"
      
    - PYTHON: "C:\\Python26-x64"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "64"        
      RUN: "%PYTHON%\\Scripts\\coverage run"
 
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\Scripts\\coverage run"
 
    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\Scripts\\coverage run"
 
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\Scripts\\coverage run"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
      RUN: "%PYTHON%\\Scripts\\coverage run"
  
#    - PYTHON: "C:\\Python26"
#      PYTHON_VERSION: "2.6.x"
#      PYTHON_ARCH: "32"  
#      RUN: "%PYTHON%\\python"

#    - PYTHON: "C:\\Python27"
#      PYTHON_VERSION: "2.7.8"
#      PYTHON_ARCH: "32"
#      RUN: "%PYTHON%\\python"
 
#    - PYTHON: "C:\\Python33"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "32"
#      RUN: "%PYTHON%\\python"
 
#    - PYTHON: "C:\\Python34"
#      PYTHON_VERSION: "3.4.1"
#      PYTHON_ARCH: "32"
#      RUN: "%PYTHON%\\python"
      
#    - PYTHON: "C:\\Python35"
#      PYTHON_VERSION: "3.5.0"
#      PYTHON_ARCH: "32"
#      RUN: "%PYTHON%\\python"
      
#    - PYTHON: "C:\\Python26-x64"
#      PYTHON_VERSION: "2.6.x"
#      PYTHON_ARCH: "64"     
#      RUN: "%PYTHON%\\python"   
 
#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.8"
#      PYTHON_ARCH: "64"
#      RUN: "%PYTHON%\\python"
 
#    - PYTHON: "C:\\Python33-x64"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "64"
#      RUN: "%PYTHON%\\python"
 
#    - PYTHON: "C:\\Python34-x64"
#      PYTHON_VERSION: "3.4.1"
#      PYTHON_ARCH: "64"
#      RUN: "%PYTHON%\\python"

#    - PYTHON: "C:\\Python35-x64"
#      PYTHON_VERSION: "3.5.0"
#      PYTHON_ARCH: "64"
#      RUN: "%PYTHON%\\python"
 
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
 
install:
#  - "powershell appveyor\\install.ps1"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"
  - "%PYTHON%\\Scripts\\pip install coverage==3.7.1 coveralls"
 
test: off
 
build_script:
  - "%RUN% %HOME%\\main.py"
  
on_success:
  - "%PYTHON%\\Scripts\\coverage xml"
  - "%PYTHON%\\Scripts\\coveralls"
 
#after_test:
#  - "%WITH_COMPILER% %PYTHON%/python setup.py %DISTRIBUTIONS%"
 
artifacts:
  - path: dist\*
